"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Aperture, ArrowLeft, ArrowRight, Award, Clapperboard, CloudUpload, Expand, Film, Image as ImageIcon, ListMusic, Moon, Music2, Pause, Play, Radio, ShieldAlert, Sparkles, Square, Upload, Volume2, Wifi, WifiOff, X } from "lucide-react";
import { Cue, initialCues } from "@/lib/show-data";

type ProgramState={scene:"idle"|"cue"|"blackout";cue:Cue|null;cueIndex:number;updatedAt:number;sequence:number};
type Asset={id:string;name:string;kind:"photo"|"audio"|"video"|"background";size:number;cueId?:string};
const LIVE_KEY="gala_program_live_v1", REHEARSAL_KEY="gala_program_rehearsal_v1", CUES_KEY="gala_cues_v1", ASSETS_KEY="gala_assets_v1";
const idleState:ProgramState={scene:"idle",cue:null,cueIndex:-1,updatedAt:Date.now(),sequence:0};
const APP_BASE=((import.meta as ImportMeta&{env?:{BASE_URL?:string}}).env?.BASE_URL||"/").replace(/\/?$/,"/");
function publicUrl(path=""){if(!path)return "";if(path.startsWith("blob:")||path.startsWith("data:")||path.startsWith("http"))return path;return APP_BASE+path.replace(/^\//,"")}

function readJson<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}}
function initials(name=""){return name.split(" ").map(x=>x[0]).join("").slice(0,2)}
function fmtTime(seconds:number){const s=Math.max(0,Math.floor(seconds));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")}
function openDb():Promise<IDBDatabase>{return new Promise((res,rej)=>{const r=indexedDB.open("gala-media",1);r.onupgradeneeded=()=>r.result.createObjectStore("files");r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveBlob(id:string,file:File){const db=await openDb();await new Promise<void>((res,rej)=>{const tx=db.transaction("files","readwrite");tx.objectStore("files").put(file,id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)});db.close()}
async function loadBlobUrl(id?:string){if(!id)return "";const db=await openDb();const blob=await new Promise<Blob|undefined>((res,rej)=>{const r=db.transaction("files").objectStore("files").get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();return blob?URL.createObjectURL(blob):""}

function Mark({small=false}:{small?:boolean}){return <div className={"mark "+(small?"small":"")} aria-label="Emblema Gala de Talentos y Fe"><span/><span/><i/></div>}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <button type="button" role="switch" aria-label={label} aria-checked={checked} className={"native-switch "+(checked?"checked":"")} onClick={()=>onChange(!checked)}><span/></button>}
function useSyncedProgram(key:string){
 const [program,setProgramLocal]=useState<ProgramState>(idleState); const bc=useRef<BroadcastChannel|null>(null);
 useEffect(()=>{setProgramLocal(readJson(key,idleState));bc.current=new BroadcastChannel("gala-control");const onMsg=(e:MessageEvent)=>{if(e.data?.key===key)setProgramLocal(e.data.state)};bc.current.addEventListener("message",onMsg);const onStorage=(e:StorageEvent)=>{if(e.key===key&&e.newValue)try{setProgramLocal(JSON.parse(e.newValue))}catch{}};window.addEventListener("storage",onStorage);return()=>{bc.current?.close();window.removeEventListener("storage",onStorage)}},[key]);
 const setProgram=useCallback((next:ProgramState)=>{setProgramLocal(next);localStorage.setItem(key,JSON.stringify(next));bc.current?.postMessage({key,state:next})},[key]);
 return [program,setProgram] as const;
}

function Scene({program,compact=false}:{program:ProgramState;compact?:boolean}){
 const [photo,setPhoto]=useState("");const [video,setVideo]=useState("");const cue=program.cue;
 useEffect(()=>{let old="";(async()=>{const u=await loadBlobUrl(cue?.photoId);old=u;setPhoto(u)})();return()=>{if(old)URL.revokeObjectURL(old)}},[cue?.photoId,program.sequence]);
 useEffect(()=>{let old="";(async()=>{const u=await loadBlobUrl(cue?.videoId);old=u;setVideo(u)})();return()=>{if(old)URL.revokeObjectURL(old)}},[cue?.videoId,program.sequence]);
 if(program.scene==="blackout")return <div className="scene blackout" aria-label="Pantalla negra"/>;
 if(program.scene==="idle"||!cue)return <div className="scene scene-idle"><div className="vignette"/><div className="particles"/><div className="idle-lockup"><Mark/><p>DECIMOTERCER SÁBADO</p><h1>GALA DE<br/><em>TALENTOS Y FE</em></h1><span>FE · LUZ · TALENTO · SERVICIO</span></div><div className="bug"><Mark small/> GALA DE TALENTOS Y FE</div></div>;
 const type=cue.type; const bg=publicUrl(type==="award"?"assets/background-award.png":type==="scripture"?"assets/background-scripture.png":"assets/background-main.png"); const imageSource=photo||publicUrl(cue.photo||""); const videoSource=video||publicUrl(cue.video||"");
 if(type==="video"&&videoSource)return <div className="scene scene-video"><video key={videoSource} src={videoSource} autoPlay playsInline muted={compact}/></div>;
 return <div key={program.sequence} className={"scene scene-"+type} style={{backgroundImage:"linear-gradient(90deg,rgba(0,0,0,.2),rgba(0,0,0,.05)),url("+bg+")"}}><div className="vignette"/><div className="particles"/>{type==="opening"?<div className="opening-sequence"><i className="light-seed"/><Mark/><p>DECIMOTERCER SÁBADO</p><h1>GALA DE<br/><em>TALENTOS Y FE</em></h1></div>:type==="award"?<div className="award-card"><Mark/><p>RECONOCIMIENTO</p><h1>{cue.title}</h1><div className="award-line"/><h2>{cue.participant}</h2><span>{cue.description}</span></div>:type==="scripture"?<div className={"scripture-layout "+(!imageSource?"without-photo":"")}>{imageSource&&<div className="scripture-portrait"><img src={imageSource} alt={cue.participant||""}/></div>}<div className="scripture-card">{cue.participant&&<p>{cue.participant} · {cue.subtitle}</p>}<blockquote>{cue.quote}</blockquote><div/><strong>{cue.reference}</strong></div></div>:type==="class"?<div className="class-card"><p>CLASE DE ADULTOS</p><h1>{cue.title}</h1><h2>“{cue.subtitle}”</h2><div/><span>{cue.description}</span></div>:type==="final"?<div className="final-card"><Mark/><h1>{cue.title}</h1><p>{cue.subtitle}</p><blockquote>{cue.quote}</blockquote><small>FIN DEL PROGRAMA</small></div>:type==="participant"||type==="video"?<div className="participant-card"><div className="portrait">{imageSource?<img src={imageSource} alt={cue.participant||""}/>:<><span>{initials(cue.participant)}</span><small>{cue.participant}</small></>}</div><div className="participant-copy"><p>GALA DE TALENTOS Y FE</p><h1>{cue.title}</h1><h2>{cue.subtitle}</h2>{cue.quote&&<blockquote>{cue.quote}</blockquote>}</div></div>:<div className="title-card"><Mark/><p>{type==="transition"?"NUEVA SECCIÓN":"GALA DE TALENTOS Y FE"}</p><h1>{cue.title}</h1><span>{cue.subtitle}</span></div>} {!compact&&type!=="final"&&<div className="bug"><Mark small/> GALA DE TALENTOS Y FE</div>}</div>
}

function PreviewFrame({program,label,tone}:{program:ProgramState;label:string;tone:"blue"|"red"}){return <div className={"frame "+tone}><div className="frame-label"><span>{label}</span><small>{program.scene==="idle"?"FONDO":program.scene==="blackout"?"BLACKOUT":program.cue?.name}</small></div><div className="frame-screen"><Scene program={program} compact/></div></div>}
export default function GalaApp(){const [path,setPath]=useState("/admin");useEffect(()=>setPath(window.location.hash.replace(/^#/,"")||window.location.pathname),[]);if(path.endsWith("/display"))return <Display/>;return <Admin rehearsalRoute={path.endsWith("/rehearsal")}/>}
function Display(){
 const [program]=useSyncedProgram(LIVE_KEY);const [fullscreen,setFullscreen]=useState(false);
 useEffect(()=>{const beat=()=>localStorage.setItem("gala_display_heartbeat",String(Date.now()));const onFullscreen=()=>setFullscreen(!!document.fullscreenElement);beat();onFullscreen();const i=setInterval(beat,1000);document.addEventListener("fullscreenchange",onFullscreen);return()=>{clearInterval(i);document.removeEventListener("fullscreenchange",onFullscreen)}},[]);
 const toggleFullscreen=()=>{if(document.fullscreenElement)void document.exitFullscreen?.();else void document.documentElement.requestFullscreen?.()};
 return <main className="display-root" onDoubleClick={toggleFullscreen}><Scene program={program}/>{!fullscreen&&<button className="display-fullscreen" onClick={toggleFullscreen} aria-label="Poner el display en pantalla completa"><Expand/> PANTALLA COMPLETA <small>DOBLE CLIC</small></button>}</main>
}

function Admin({rehearsalRoute}:{rehearsalRoute:boolean}){
 const [mode,setMode]=useState<"live"|"rehearsal">(rehearsalRoute?"rehearsal":"live");const [live,setLive]=useSyncedProgram(LIVE_KEY);const [rehearsal,setRehearsal]=useSyncedProgram(REHEARSAL_KEY);const program=mode==="live"?live:rehearsal;const setProgram=mode==="live"?setLive:setRehearsal;
 const [cues,setCues]=useState<Cue[]>(initialCues),[selected,setSelected]=useState(2),[assets,setAssets]=useState<Asset[]>([]),[clock,setClock]=useState(new Date(0)),[started]=useState(Date.now()),[connected,setConnected]=useState(false),[preloading,setPreloading]=useState(false),[showReady,setShowReady]=useState(false),[autoAssist,setAutoAssist]=useState(false),[dragging,setDragging]=useState<number|null>(null),[toolTab,setToolTab]=useState<"controls"|"audio"|"media"|"editor">("controls");
 const [audioUrl,setAudioUrl]=useState(""),[audioName,setAudioName]=useState("Sin música de fondo"),[volume,setVolume]=useState(.18),[loop,setLoop]=useState(true),[audioPlaying,setAudioPlaying]=useState(false);const audioRef=useRef<HTMLAudioElement>(null);const timers=useRef<number[]>([]);const fadeTimer=useRef<number|null>(null);
 function fadeMusic(target:number,pauseAtEnd=false){const a=audioRef.current;if(!a)return;if(fadeTimer.current!==null)window.clearInterval(fadeTimer.current);const start=a.volume;let n=0;fadeTimer.current=window.setInterval(()=>{n++;const nextVolume=Math.max(0,Math.min(.35,start+(target-start)*(n/24)));a.volume=nextVolume;setVolume(nextVolume);if(n>=24){if(fadeTimer.current!==null)window.clearInterval(fadeTimer.current);fadeTimer.current=null;if(pauseAtEnd&&target===0){a.pause();setAudioPlaying(false)}}},70)}
 function cueMusic(){fadeMusic(0,true)}
 useEffect(()=>{if(audioRef.current)audioRef.current.volume=volume},[volume]);
 useEffect(()=>{const saved=readJson<Cue[]>(CUES_KEY,initialCues);const defaults=new Map(initialCues.map(c=>[c.id,c]));const merged:Cue[]=saved.map(c=>{const base=defaults.get(c.id);const next={...base,...c,photo:c.photo||base?.photo};if(c.id==="cloey")return {...next,name:"Chloe — Flauta",participant:"CHLOE",title:"CHLOE"};if(c.id==="award-cloey")return {...next,participant:"CHLOE"};return next});initialCues.forEach((c,defaultIndex)=>{if(merged.some(x=>x.id===c.id))return;const previousIds=initialCues.slice(0,defaultIndex).map(x=>x.id).reverse();let previousIndex=-1;for(const id of previousIds){const found=merged.findIndex(x=>x.id===id);if(found>=0){previousIndex=found;break}}if(previousIndex>=0)merged.splice(previousIndex+1,0,c);else merged.push(c)});setCues(merged);setAssets(readJson(ASSETS_KEY,[]));const i=setInterval(()=>{setClock(new Date());setConnected(Date.now()-Number(localStorage.getItem("gala_display_heartbeat")||0)<3000)},1000);return()=>{clearInterval(i);timers.current.forEach(clearTimeout);if(fadeTimer.current!==null)window.clearInterval(fadeTimer.current)}},[]);
 useEffect(()=>localStorage.setItem(CUES_KEY,JSON.stringify(cues)),[cues]);useEffect(()=>localStorage.setItem(ASSETS_KEY,JSON.stringify(assets)),[assets]);
 const preview:ProgramState={scene:"cue",cue:cues[selected]||null,cueIndex:selected,updatedAt:Date.now(),sequence:program.sequence};const nextCue=cues[Math.min(program.cueIndex<0?selected:program.cueIndex+1,cues.length-1)];
 const push=useCallback((state:Partial<ProgramState>)=>setProgram({...program,...state,updatedAt:Date.now(),sequence:program.sequence+1}),[program,setProgram]);const take=(index=selected)=>{const cue=cues[index];if(!cue)return;cueMusic();push({scene:"cue",cue,cueIndex:index});setSelected(Math.min(index+1,cues.length-1));if(autoAssist&&cue.autoClear){const t=window.setTimeout(()=>{fadeMusic(0,true);push({scene:"idle",cue:null})},Math.max(3,cue.duration||7)*1000);timers.current.push(t)}};
 const background=()=>{fadeMusic(0,true);push({scene:"idle",cue:null})},blackout=()=>{fadeMusic(0,true);push({scene:"blackout",cue:null})};const previous=()=>setSelected(x=>Math.max(0,x-1)),next=()=>setSelected(x=>Math.min(cues.length-1,x+1));const awardTake=()=>{const person=program.cue?.participant||cues[selected]?.participant;const i=cues.findIndex(c=>c.type==="award"&&c.participant===person);if(i>=0)take(i)};
 const toggleAudio=useCallback(()=>{const a=audioRef.current;if(!a||!audioUrl)return;if(a.paused){void a.play();setAudioPlaying(true)}else{a.pause();setAudioPlaying(false)}},[audioUrl]);const stopAudio=()=>{const a=audioRef.current;if(!a)return;a.pause();a.currentTime=0;setAudioPlaying(false)};
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(["INPUT","TEXTAREA","SELECT"].includes((e.target as HTMLElement)?.tagName))return;if(e.code==="Space"){e.preventDefault();take()}else if(e.key==="Escape"||e.key.toLowerCase()==="b")background();else if(e.key.toLowerCase()==="x")blackout();else if(e.key.toLowerCase()==="a")awardTake();else if(e.key==="ArrowLeft")previous();else if(e.key==="ArrowRight")next();else if(e.key.toLowerCase()==="m")toggleAudio()};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)});
 const preload=()=>{setPreloading(true);["assets/background-main.png","assets/background-award.png","assets/background-scripture.png"].forEach(src=>{const i=new Image();i.src=publicUrl(src)});cues.filter(c=>c.video).forEach(c=>{const video=document.createElement("video");video.preload="auto";video.src=publicUrl(c.video!)});setTimeout(()=>{setPreloading(false);setShowReady(true)},1300)};
 const onUpload=async(kind:Asset["kind"],file?:File)=>{if(!file)return;const id=crypto.randomUUID();await saveBlob(id,file);const asset={id,name:file.name,kind,size:file.size,cueId:cues[selected]?.id};setAssets(x=>[asset,...x]);if(kind==="audio"){setAudioUrl(await loadBlobUrl(id));setAudioName(file.name)}else setCues(x=>x.map((c,i)=>i===selected?{...c,[kind==="photo"?"photoId":kind==="video"?"videoId":"backgroundId"]:id}:c))};
 const reorder=(to:number)=>{if(dragging===null||dragging===to)return;setCues(x=>{const y=[...x];const m=y.splice(dragging,1)[0];y.splice(to,0,m);return y});setSelected(to);setDragging(null)};const updateCue=(field:keyof Cue,value:string|number|boolean)=>setCues(x=>x.map((c,i)=>i===selected?{...c,[field]:value}:c));
 return <main className={"admin-root "+(mode==="rehearsal"?"rehearsal-mode":"")}>{audioUrl&&<audio ref={audioRef} src={audioUrl} loop={loop} onEnded={()=>setAudioPlaying(false)}/>}
  <header className="admin-top"><div className="admin-brand"><Mark/><div><strong>GALA CONTROL</strong><small>DECIMOTERCER SÁBADO</small></div></div><div className="live-cluster"><button className={mode==="live"?"live-pill":"rehearsal-pill"} onClick={()=>setMode(mode==="live"?"rehearsal":"live")}>{mode==="live"?"● LIVE":"◉ ENSAYO"}</button><span className={connected?"online":"offline"}>{connected?<Wifi/>:<WifiOff/>} DISPLAY {connected?"CONECTADO":"DESCONECTADO"}</span></div><div className="admin-clock"><b suppressHydrationWarning>{clock.getTime()?clock.toLocaleTimeString("es",{hour12:false}):"--:--:--"}</b><small suppressHydrationWarning>TRANSCURRIDO · {fmtTime((Date.now()-started)/1000)}</small></div></header>
  <section className="now-next"><div><span>AHORA EN PANTALLA</span><strong>{program.scene==="idle"?"FONDO PRINCIPAL":program.scene==="blackout"?"BLACKOUT":program.cue?.name||"—"}</strong></div><i/><div><span>SIGUIENTE</span><strong>{nextCue?.name||"FIN DEL SHOW"}</strong></div><label><span>AUTO ASSIST</span><Toggle label="Auto Assist" checked={autoAssist} onChange={setAutoAssist}/></label></section>
  <section className="admin-grid"><aside className="run-sheet"><div className="panel-title"><span>RUN OF SHOW</span><small>{cues.length} CUES</small></div><div className="cue-scroll">{cues.map((cue,i)=><button draggable onDragStart={()=>setDragging(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>reorder(i)} onClick={()=>setSelected(i)} className={"cue "+(selected===i?"selected ":"")+(program.cue?.id===cue.id?"on-air":"")} key={cue.id}><b>{String(i+1).padStart(2,"0")}</b><span>{cue.name}<small>{cue.type.toUpperCase()} {cue.participant?"· "+cue.participant:""}</small></span><em>{program.cue?.id===cue.id?"EN VIVO":selected===i?"PREPARADO":"PENDIENTE"}</em></button>)}</div></aside>
  <section className="production"><div className="monitors"><PreviewFrame program={preview} label="PREVIEW" tone="blue"/><PreviewFrame program={program} label="PROGRAM OUTPUT" tone="red"/></div><div className="primary-actions"><button className="ghost"><Clapperboard/> PREPARAR</button><button className="take" onClick={()=>take()}><Radio/> DAR PASO <kbd>SPACE</kbd></button><button className="award-btn" onClick={awardTake}><Award/> PREMIO</button></div><div className="failsafe"><button onClick={background}><Aperture/> FONDO <kbd>B</kbd></button><button onClick={previous}><ArrowLeft/> ANTERIOR</button><button onClick={next}>SIGUIENTE <ArrowRight/></button><button onClick={background}><X/> CLEAR <kbd>ESC</kbd></button><button className="danger" onClick={blackout}><Moon/> BLACKOUT <kbd>X</kbd></button></div>
  <div className="tool-tabs"><div className="tab-list">{(["controls","audio","media","editor"] as const).map(tab=><button key={tab} className={toolTab===tab?"active":""} onClick={()=>setToolTab(tab)}>{tab==="controls"?"CONTROL":tab.toUpperCase()}</button>)}</div>
   {toolTab==="controls"&&<div className="tab-panel"><div className="control-cards"><div className="control-card"><div><span>MODO DE OPERACIÓN</span><b>{mode==="live"?"SALIDA PÚBLICA":"ENTORNO SEGURO"}</b></div><button onClick={()=>setMode(mode==="live"?"rehearsal":"live")}>{mode==="live"?"CAMBIAR A ENSAYO":"CAMBIAR A LIVE"}</button></div><div className="control-card"><div><span>DISPLAY</span><b>VENTANA LIMPIA 16:9</b></div><button onClick={()=>window.open(APP_BASE+"#/display","gala-display","popup,width=1280,height=720")}><Expand/> ABRIR DISPLAY</button></div><div className="control-card"><div><span>PRECARGA</span><b>{showReady?"TODO LISTO":preloading?"CARGANDO ASSETS…":"LISTO PARA VERIFICAR"}</b></div><button onClick={preload} disabled={preloading}><CloudUpload/> {preloading?"PRECARGANDO":"PRELOAD SHOW"}</button></div></div>{showReady&&<div className="ready-row"><span>✓ Imágenes</span><span>✓ Sin música</span><span>✓ Video</span><span>{connected?"✓ Display":"○ Display pendiente"}</span><b>SHOW READY</b></div>}</div>}
   {toolTab==="audio"&&<div className="tab-panel"><div className="audio-board"><div className="audio-track"><ListMusic/><div><strong>{audioName}</strong><span>LA GALA SE REPRODUCIRÁ SIN CANCIÓN DE FONDO</span></div>{audioUrl&&<label className="upload-mini"><Upload/><input type="file" accept="audio/*" onChange={e=>onUpload("audio",e.target.files?.[0])}/></label>}</div>{audioUrl&&<div className="transport"><button onClick={toggleAudio}>{audioPlaying?<Pause/>:<Play/>}</button><button onClick={stopAudio}><Square/></button><button onClick={()=>fadeMusic(0,true)}>DETENER</button><label><Volume2/><input type="range" min="0" max=".35" step=".01" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);if(audioRef.current)audioRef.current.volume=v}}/></label><label>LOOP <Toggle label="Loop" checked={loop} onChange={setLoop}/></label></div>}</div></div>}
   {toolTab==="media"&&<div className="tab-panel"><div className="media-grid">{(["photo","video","audio"] as const).map(kind=><label className="media-upload" key={kind}>{kind==="photo"?<ImageIcon/>:kind==="video"?<Film/>:<Music2/>}<b>{kind==="photo"?"CARGAR FOTO":kind==="video"?"CARGAR VIDEO":"CARGAR AUDIO"}</b><span>Asignar a {cues[selected]?.name}</span><input type="file" accept={kind==="photo"?"image/jpeg,image/png,image/webp":kind==="video"?"video/*":"audio/*"} onChange={e=>onUpload(kind,e.target.files?.[0])}/></label>)}<div className="asset-list"><b>MEDIA RECIENTE</b>{assets.slice(0,5).map(a=><span key={a.id}>{a.kind.toUpperCase()} · {a.name}<small>{(a.size/1048576).toFixed(1)} MB</small></span>)}</div></div></div>}
   {toolTab==="editor"&&<div className="tab-panel"><div className="cue-editor"><label>NOMBRE DEL CUE<input value={cues[selected]?.name||""} onChange={e=>updateCue("name",e.target.value)}/></label><label>TÍTULO<input value={cues[selected]?.title||""} onChange={e=>updateCue("title",e.target.value)}/></label><label>SUBTÍTULO<input value={cues[selected]?.subtitle||""} onChange={e=>updateCue("subtitle",e.target.value)}/></label><label>PARTICIPANTE<input value={cues[selected]?.participant||""} onChange={e=>updateCue("participant",e.target.value)}/></label><label className="wide">DESCRIPCIÓN / FRASE<textarea value={cues[selected]?.description||cues[selected]?.quote||""} onChange={e=>updateCue(cues[selected]?.type==="scripture"?"quote":"description",e.target.value)}/></label><label>DURACIÓN<input type="number" value={cues[selected]?.duration||7} onChange={e=>updateCue("duration",Number(e.target.value))}/></label><label className="toggle-label">AUTO CLEAR <Toggle label="Auto clear" checked={!!cues[selected]?.autoClear} onChange={v=>updateCue("autoClear",v)}/></label></div></div>}
  </div></section>
  <aside className="side-panel"><div className="panel-title"><span>SYSTEM</span><small>ESTADO</small></div>{[[connected?<Wifi/>:<WifiOff/>,"DISPLAY",connected?"Connected":"Offline",connected],[<Volume2/>,"AUDIO",audioUrl?"Ready":"Standby",!!audioUrl],[<Film/>,"VIDEO",assets.some(a=>a.kind==="video")||cues.some(c=>!!c.video)?"Ready":"Standby",assets.some(a=>a.kind==="video")||cues.some(c=>!!c.video)],[<Sparkles/>,"MEDIA",assets.length?assets.length+" loaded":"Local",true],[<Radio/>,"SYNC","Online",true]].map(([icon,a,b,ok]:any)=><div className="system-row" key={a}>{icon}<span>{a}<small>{b}</small></span><i className={ok?"ok":"warn"}/></div>)}<button className={"preload "+(showReady?"ready":"")} onClick={preload}>{showReady?"✓ SHOW READY":preloading?"PRECARGANDO…":"PRELOAD SHOW"}</button><div className="shortcut-card"><b>ATAJOS</b><span><kbd>SPACE</kbd> TAKE</span><span><kbd>ESC</kbd> CLEAR</span><span><kbd>B</kbd> FONDO</span><span><kbd>X</kbd> BLACKOUT</span><span><kbd>A</kbd> PREMIO</span><span><kbd>← →</kbd> NAVEGAR</span></div><button className="stop-all" onClick={()=>{stopAudio();blackout()}}><ShieldAlert/> EMERGENCIA<br/><small>STOP AUDIO + BLACKOUT</small></button></aside></section>
 </main>
}
